### ISSUE TITLE
Check conjunction direction

### ISSUE THREAD

**Issue by alemelis** [INSIGNEO/openBF#26]
Two joined vessels should defined as

```yaml
v1:
  sn: 1
  tn: 2
v2:
  sn: 2
  tn: 3
```

whereas

```yaml
v1:
  sn: 1
  tn: 2
v2:
  sn: 3
  tn: 2
```

shouldn't be allowed
